# Default values for clickhouse.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry-vpc.cn-hangzhou.aliyuncs.com/thundersdata-public/clickhouse:2021-1-29
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: "clickhouse"

pvc:
  name: clickhouse
  size: 10Gi

imagePullSecrets:
  enabled: true
  name: regsecret

service:
  type: NodePort
  port: 8123

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 500Mi

nodeSelector: {}

tolerations: []

affinity: {}
