apiVersion: v1
data:
  file.conf: |+
    store {
      mode = "db"

      db {
        datasource = "druid"
        dbType = "mysql"
        driverClassName = "com.mysql.jdbc.Driver"
        url = "jdbc:mysql://{{ .Values.db.host }}:{{ .Values.db.port }}/{{ .Values.db.dbname }}"
        user = "{{ .Values.db.user }}"
        password = "{{ .Values.db.password }}"
        minConn = 5
        maxConn = 30
        globalTable = "global_table"
        branchTable = "branch_table"
        lockTable = "lock_table"
        queryLimit = 100
        maxWait = 5000
      }
    }

kind: ConfigMap
metadata:
  name: seata-server
