apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "seata.fullname" . }}
  labels:
    app: seata
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: seata
  template:
    metadata:
      labels:
        app: seata
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: STORE_MODE
              value: db
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
          volumeMounts:
          - name: seata-config
            mountPath: /seata-server/resources/file.conf
            subPath: file.conf
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: seata-config
        configMap:
          name: seata-server
          items:
          - key: file.conf
            path: file.conf
