apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysqlbackup
  namespace: tools
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - /bin/bash
            - /root/backup.sh
            env:
            - name: storagepath
              value: /storagepath
            - name: mysqlhost
              value: "HOST"
            - name: mysqlport
              value: "PORT"
            - name: mysqlpassword
              value: "PASSWORD"
            image: bubaoxiaoyu/backup_etcd-mysql:v1
            imagePullPolicy: IfNotPresent
            name: backup
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /storagepath
              name: storage
            - mountPath: /root/backup.sh
              name: run
              subPath: backup.sh
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: storage
            persistentVolumeClaim:
              claimName: mysqlbackup
          - configMap:
              defaultMode: 420
              name: mysqlbackup
            name: run
  schedule: 0 22 * * *