# Default values for kafka-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: provectuslabs/kafka-ui:latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: "kafka-ui"

service:
  type: NodePort
  port: 8080

# name is first kafka name
# bootstrapservers is kafka url
kafka:
  name: local
  bootstrapservers: 192.168.0.71:9092

imagePullSecrets:
  enabled: true
  name: regsecret

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: kafka.local.com
      paths: ['/']

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 1
    memory: 3Gi

nodeSelector: {}

tolerations: []

affinity: {}
