apiVersion: v1
data:
  master_host: MASTERHOST
  master_password: MASTERPD
  master_root_password: MASTERROOTPD
  master_port: MASTERPORT
  master_user: MASTERUSER
  mysql_password: LOCALPD
  mysql_root_password: LOCALPD
kind: Secret
metadata:
  name: mysql-slave1
  namespace: tools
type: Opaque
