apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-slave1
  name: mysql-slave1
  namespace: tools
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-slave1
  sessionAffinity: None
  type: ClusterIP