apiVersion: v1
data:
  rsync-backup.sh: "#!/bin/bas\n# rsync.sh\n# 镜像为 bubaoxiaoyu/rsync:ubuntu\n#
    本地执行命令\n# rsync -aqutz 需要备份目录 备份到目录\n# 远程执行命令为\n#　rsync -aqutz 备份用户@远程ip::备份模块
    备份到本机目录 --password-file=密文文件\n# 这里默认是本地备份, 且需要备份目录为/source, 备份到的目录为/dest, 且记录结果到/dest/rsync-backup.log,
    保留1000条\n\n# 记录日期时间\nnowTime=`date +\"%Y-%m-%d_%H:%M:%S\"`\nstartTime=`date +\"%s\"`\nsource=\"/source\"\ndest=\"/dest\"\n\n#
    执行命令\nrsync -aqutz ${source} ${dest}\n\n# 写日志\nresult=`echo $?`\nendTime=`date
    +\"%s\"`\necho \"${nowTime} 备份结果: ${result}, 耗费时长 $((endTime - startTime)) 秒!\"
    >> ${dest}/rsync-backup.log\n\n# 清空超出日志\nif [[ `cat ${dest}/rsync-backup.log|wc
    -l` -gt 1000 ]]; then\n\told_log=`head -n 1 ${dest}/rsync-backup.log`\n\tsed -i
    '/${old_log}/d' ${dest}/rsync-backup.log\nfi\n\n"
kind: ConfigMap
metadata:
  name: rsync-backup
  namespace: tools
