apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rsync-backup
  namespace: tools
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/bash
            - /root/rsync-backup.sh
            image: bubaoxiaoyu/rsync:ubuntu
            imagePullPolicy: IfNotPresent
            name: rsync
            resources:
              requests:
                cpu: 100m
                memory: 300Mi
              limits:
                cpu: 200m
                memory: 500Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /root/rsync-backup.sh
              name: run
              subPath: rsync-backup.sh
            - name: dest
              mountPath: /dest
            - name: source
              mountPath: /source
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: rsync-backup
            name: run
          - name: dest
            persistentVolumeClaim:
              claimName: rsync-backup-dest
          - name: source
            hostPath:
              path: /mnt
  schedule: '0 11 * * *'
  suspend: false