apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: rsync-backup-dest
  name: rsync-backup-dest
  namespace: tools
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi