apiVersion: v1
data:
  master_password: {{ .Values.slave.password | b64enc | quote }}
  master_root_password: {{ .Values.mysqlRootPassword | b64enc | quote }}
  master_user: {{ .Values.slave.user | b64enc | quote }}
  mysql_password: {{ .Values.mysqlRootPassword | b64enc | quote }}
  mysql_root_password: {{ .Values.mysqlRootPassword | b64enc | quote }}
kind: Secret
metadata:
  name: mysql-slave-config
type: Opaque
