apiVersion: v1
data:
  mysqld.cnf: |-
    [mysqld]
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql
    log-error       = /var/log/mysql/error.log
    server-id       = SERVERID
    relay-log = /var/log/mysql/mysql-relay-bin
    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0
    max_connections=3000
    max_user_connections=300
    expire_logs_days = 1
    read_only = 1
    log_slave_updates = 1
    innodb_force_recovery=0
    character_set_server = utf8
    performance-schema-instrument='memory/%=COUNTED'
kind: ConfigMap
metadata:
  name: mysqld-slave-conf
