apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  annotations:
        descript: "mysql ha, one master, one slave."
  labels:
    app: mysql-master
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app: mysql-master
