apiVersion: v1
kind: Secret
metadata:
  name: mysql
  annotations:
        descript: "mysql ha, one master, one slave."
  labels:
    app: mysql-master
type: Opaque
data:
  mysql-root-password:  {{ .Values.mysqlRootPassword | b64enc | quote }}
  mysql-password:  {{ .Values.mysqlPassword | b64enc | quote }}
