apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: thunderbi-schedule
  name: thunderbi-schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thunderbi-schedule
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: thunderbi-schedule
    spec:
      containers:
      - args:
        - dev_scheduler
        envFrom:
        - configMapRef:
            name: thunderbi-env
        image: registry-vpc.cn-hangzhou.aliyuncs.com/thundersdata-public/thunderbi_base_image:v0.1.0
        imagePullPolicy: IfNotPresent
        name: thunderbi-schedule
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      initContainers:
      - env:
        - name: tcp_port
          value: "5000"
        - name: tcp_ip
          value: thunderbi-server
        image: bubaoxiaoyu/init-container:check-port
        imagePullPolicy: IfNotPresent
        name: init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: regsecret

