apiVersion: v1
kind: Service
metadata:
  labels:
    app: thunderbi-email
  name: thunderbi-email
spec:
  ports:
  - port: 80
    name: http1
    protocol: TCP
    targetPort: 80
  selector:
    app: thunderbi-email
  sessionAffinity: None
  type: ClusterIP