actions:
  1:
    action: delete_indices
    options:
      ignore_empty_list: True
      continue_if_exception: True
    filters:
    - filtertype: pattern
      kind: timestring
      value: '%Y-%m-%d'
      exclude: False
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y-%m-%d'
      unit: days
      unit_count: 15
  2:
    action: delete_indices
    options:
      ignore_empty_list: True
      continue_if_exception: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: 'test'
      exclude: False
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y-%m-%d'
      unit: minutes
      unit_count: 1