apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka-simple.fullname" . }}
  labels:
    app: kafka-simple
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kafka-simple
