apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka-ui.fullname" . }}
  labels:
{{ include "kafka-ui.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "kafka-ui.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
