# Default values for mysqlha.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: mysql:5.7.14


mysqlRootPassword: MYSQLPASSWD
mysqlPassword: MYSQLPASSWD

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3306

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
persistence:
  enabled: true
  size: MYSQLSIZE

slave:
  user: slave
  password: slave@123
  replicaCount: 2
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 2
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}
